SLACK_TOKEN = ("YOUR SLACK TOKEN HERE")
SLACK_CHANNEL = ("#YOURCHANNEL")
DISCORD_WEBHOOK_URL = ""

RESULTS_COUNT = 100
FREQUENCY = 300
FREQUENCY_SLOW = 600
DELAY_START = "00:00"
DELAY_STOP = "01:00"

ITEMS = ["nintendo switch", ]

LIMIT_1 = 1